// <auto-generated />
using System;
using Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bot.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bot.Models.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("admins");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "admin",
                            password = "1234"
                        });
                });

            modelBuilder.Entity("Bot.Models.Barber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("special")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("barbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Светлана",
                            special = "✂️ Мужская стрижка"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Анастасия",
                            special = "🎨 Окрашивание"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Алина",
                            special = "💇‍♀️ Женская стрижка"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Людмила",
                            special = "💆‍♂️ Уход за волосами"
                        });
                });

            modelBuilder.Entity("Bot.Models.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BarberId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BookDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BookTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BarberId");

                    b.HasIndex("UserId");

                    b.ToTable("books");
                });

            modelBuilder.Entity("Bot.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SelectedBarberId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SelectedDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SelectedService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("currentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SelectedBarberId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Bot.Models.Books", b =>
                {
                    b.HasOne("Bot.Models.Barber", "Barber")
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bot.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bot.Models.User", b =>
                {
                    b.HasOne("Bot.Models.Barber", "SelectedBarber")
                        .WithMany()
                        .HasForeignKey("SelectedBarberId");

                    b.Navigation("SelectedBarber");
                });
#pragma warning restore 612, 618
        }
    }
}
